var pubs = [
    ["Daniel Barrett, Scott Bronikowski, <b>Haonan Yu</b>, Jeffrey Mark Siskind",
     "Driving Under the Influence (of Language)",
     "",
     "IEEE Transactions on Neural Networks and Learning Systems (TNNLS)",
     "2016",
     "In review",
     ""],
    ["Daniel Barrett, Ran Xu, <b>Haonan Yu</b>, Jeffrey Mark Siskind",
     "Collecting and Annotating the Large Continuous Action Dataset",
     "./papers/mva2016.pdf",
     "Machine Vision and Applications (MVA)",
     "2016",
     "Accepted",
     "<a href='http://upplysingaoflun.ecn.purdue.edu/~qobi/lca.tgz'>The LCA dataset</a> (7.8GB)"],
    ["<b>Haonan Yu</b>, Jiang Wang, Zhiheng Huang, Yi Yang, Wei Xu",
     "Video Paragraph Captioning Using Hierarchical Recurrent Neural Networks",
     "http://arxiv.org/pdf/1510.07712v2.pdf",
     "IEEE Conference on Computer Vision and Pattern Recognition (CVPR)",
     "2016",
     "<b>Oral</b>",
     "<a href='./datasets/youtubeclips.zip'>"
     +"YouTubeClips</a> dataset (1.8GB) from the Youtube2text paper [Guadarrama <i>et al.</i>, 2013]"],
    ["<b>Haonan Yu</b>, Jeffrey Mark Siskind",
     "Sentence Directed Video Object Codetection",
     "http://arxiv.org/pdf/1506.02059v2.pdf",
     "arXiv preprint",
     "2015",
     "",
     ""],
    ["<b>Haonan Yu</b>, Siddharth Narayanaswamy, Andrei Barbu, Jeffrey Mark Siskind",
     "A Compositional Framework for Grounding Language Inference, Generation, and Acquisition in Video",
     "./papers/jair2015.pdf",
     "Journal of Artiﬁcial Intelligence Research (JAIR)",
     "2015",
     "<b>in Award-Winning Paper Track</b>",
     ""],
    ["<b>Haonan Yu</b>, Jeffrey Mark Siskind",
     "Learning to Describe Video with Weak Supervision by Exploiting Negative Sentential Information",
     "./papers/aaai2015.pdf",
     "AAAI Conference on Artificial Intelligence (AAAI)",
     "2015",
     "<b>Oral</b>",
     ""],
    ["<b>Haonan Yu</b>, Jeffrey Mark Siskind",
     "Grounded Language Learning from Video Described with Sentences",
     "./papers/acl2013.pdf",
     "Proceedings of the Annual Meeting of the Association for Computational Linguistics (ACL)",
     "2013",
     "<b>Best Paper Award</b>",
     "<a href='./slides/talk.pdf'>Slides</a> | <a href='./datasets/acl2013-dataset.zip'>Dataset</a> (105MB)"],
    ["Yu Cao, Daniel Barrett, Andrei Barbu, Siddharth Narayanaswamy, <b>Haonan Yu</b>, Aaron Michaux, Yuewei Lin, Sven Dickinson, Jeffrey Siskind, Song Wang",
     "Recognizing Human Activities from Partially Observed Videos",
     "./papers/cvpr2013.pdf",
     "IEEE Conference on Computer Vision and Pattern Recognition (CVPR)",
     "2013",
     "",
     ""],
    ["<b>Haonan Yu</b>, Jia Li, Yonghong Tian, Tiejun Huang",
     "Automatic Interesting Object Extraction From Images Using Complementary Saliency Maps",
     "./papers/acmmm2010.pdf",
     "ACM Multimedia (ACMMM)",
     "2010",
     "",
     ""]
];
