var pubs = [
    ["<b>Haonan Yu</b>, Jiang Wang, Zhiheng Huang, Yi Yang, Wei Xu",
     "Video Paragraph Captioning using Hierarchical Recurrent Neural Networks",
     "http://arxiv.org/pdf/1510.07712v1.pdf",
     "arXiv preprint",
     "2015",
     "*NONE*"],
    ["<b>Haonan Yu</b>, Jeffrey Mark Siskind",
     "Sentence Directed Video Object Codetection",
     "http://arxiv.org/pdf/1506.02059v2.pdf",
     "arXiv preprint",
     "2015",
     "*NONE*"],
    ["<b>Haonan Yu</b>, Siddharth Narayanaswamy, Andrei Barbu, Jeffrey Mark Siskind",
     "A Compositional Framework for Grounding Language Inference, Generation, and Acquisition in Video",
     "http://haonanyu.com/papers/jair2015.pdf",
     "Journal of Artiﬁcial Intelligence Research (JAIR)",
     "2015",
     "<b>in Award-Winning Paper Track</b>"],
    ["<b>Haonan Yu</b>, Jeffrey Mark Siskind",
     "Learning to Describe Video with Weak Supervision by Exploiting Negative Sentential Information",
     "http://haonanyu.com/papers/aaai2015.pdf",
     "AAAI Conference on Artificial Intelligence",
     "2015",
     "*NONE*"],
    ["<b>Haonan Yu</b>, Jeffrey Mark Siskind",
     "Grounded Language Learning from Video Described with Sentences",
     "http://haonanyu.com/papers/acl2013.pdf",
     "Proceedings of the Annual Meeting of the Association for Computational Linguistics (ACL)",
     "2013",
     "<b>Best Paper Award</b>"],
    ["Yu Cao, Daniel Barrett, Andrei Barbu, Siddharth Narayanaswamy, <b>Haonan Yu</b>, Aaron Michaux, Yuewei Lin, Sven Dickinson, Jeffrey Siskind, Song Wang",
     "Recognizing Human Activities from Partially Observed Videos",
     "http://haonanyu.com/papers/cvpr2013.pdf",
     "IEEE Conference on Computer Vision and Pattern Recognition (CVPR)",
     "2013",
     "*NONE*"],
    ["<b>Haonan Yu</b>, Jia Li, Yonghong Tian, Tiejun Huang",
     "Automatic interesting object extraction from images using complementary saliency maps",
     "http://haonanyu.com/papers/acmmm2010.pdf",
     "ACM Multimedia (ACMMM)",
     "2010",
     "*NONE*"]
];
